export const SIMPLE_ACTION = "SIMPLE_ACTION";
export const CREATE_SERVER_NODE = "CREATE_SERVER_NODE";
export const CREATE_FIREWALL_NODE = "CREATE_FIREWALL_NODE";
export const CREATE_ROUTER_NODE = "CREATE_ROUTER_NODE";
export const CREATE_EDGE = "CREATE_EDGE";
export const FETCH_TEMPLATES_REQUEST = "FETCH_TEMPLATES_REQUEST";
export const FETCH_TEMPLATES_SUCCESS = "FETCH_TEMPLATES_SUCCESS";
export const FETCH_TEMPLATES_FAILURE = "FETCH_TEMPLATES_FAILURE";
export const FETCH_NODE_DATA_REQUEST = "FETCH_NODE_DATA_REQUEST";
export const FETCH_NODE_DATA_SUCCESS = "FETCH_NODE_DATA_SUCCESS";
export const FETCH_NODE_DATA_FAILURE = "FETCH_NODE_DATA_FAILURE";
 