export const SIMPLE_ACTION = "SIMPLE_ACTION";
export const CREATE_SERVER_NODE = "CREATE_SERVER_NODE";
export const CREATE_FIREWALL_NODE = "CREATE_FIREWALL_NODE";
export const CREATE_ROUTER_NODE = "CREATE_ROUTER_NODE";
export const CREATE_EDGE = "CREATE_EDGE";